### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by jonatant** [Contentify/Contentify#346]
Hello. Bug in admin panel: If i press "Create new" i getting error: View [admin_news_form] not found...
And thats for all pages.
View [admin_images_form] not found.
View [admin_images_form] not found.
View [admin_downloads_form] not found.

Any ideas? :)

**Comment by kamohy** [comment]
version of contentify? 2.2 / 2.3 or 2.4 ?

**Comment by jonatant** [comment]
@kamohy 2.4

**Comment by kamohy** [comment]
2.4 is a beta
Use 2.3 
the beta, does not work bugfree #342 #297

**Comment by chriskonnertz** [comment]
Hello @jonatant 

Do you have the latest commits of the 2.4-dev branch? I made some changes that could cause this bug but then again newer changes should fix it...

**Comment by jonatant** [comment]
@chriskonnertz thanks for replay. Yes i have latest 2.4-dev branch :) Bug still exist

**Comment by chriskonnertz** [comment]
I do not know how to help here. If this error would occur on my own PC / installation I would start to debug it. 

If your Contentify installation does not include critical data you could create a .zip archive and a database dump and send both to me, so I can debug the error. You could clear the `password` column in the `users` table so I cannot access passwords. You should also remove any API keys (STEAM, Twitch...). Maybe it makes also sense to delete the error log file, because it could contain such as MySQL connection data. Ofc, you should also remove these from the `storage/app/database.ini`.

You can send it via email to:   contact@contentify.org

**Comment by chriskonnertz** [comment]
Solution: https://github.com/Contentify/Contentify/issues/360
